name: 'Setup mkr'
description: 'Setup mkr - CLI for Mackerel'
author: 'Susisu <susisu2413@yahoo.co.jp>'
inputs:
  mkr-version:
    description: 'The version of mkr to use.'
runs:
  using: 'node12'
  main: 'dist/index.js'
