name: 'Setup mkr'
description: 'Setup mkr - CLI for Mackerel'
author: 'Susisu <susisu2413@yahoo.co.jp>'
inputs:
  version:
    description: 'The version of mkr to install.'
runs:
  using: 'node12'
  main: 'dist/index.js'
