name: 'Test Run'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of mkr to install.'

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: ${{ github.event.inputs.version }}
      - run: mkr org
        env:
          MACKEREL_APIKEY: ${{ secrets.TEST_MACKEREL_APIKEY }}
