name: 'Test Run'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of mkr to install.'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: ${{ github.event.inputs.version }}
